### ISSUE TITLE
配置Prometheus服务发现

### ISSUE THREAD

**Issue by smallfish01** [vovolie/lua-nginx-prometheus#1]
您好！
能否麻烦详细给个关于Prometheus配置Consul 服务发现的例子？我在Consul官方网站下载了软件，解压缩后是一个consul的可执行程序，模具前不清楚Prometheus如何配置服务发现，其它模块都已经安装好了。

谢谢！

**Comment by vovolie** [comment]
consul下载后的确是只有一个可执行程序。如果只是单机跑的话，可以直接当成一个agent来用。
`consul agent -data-dir=/tmp/consul`
这样就跑起来了，集群方式请参考官方文档了。
Prometheus有专门的consul配置项
https://prometheus.io/blog/2015/06/01/advanced-service-discovery/#discovery-with-consul
这里有一个详细说明。

**Comment by smallfish01** [comment]
好的谢谢您！ /tmp/consul这里是用来放临时文件的嘛？还是存放日志？

**Comment by vovolie** [comment]
会存放注册的服务。一堆json文件。
