### ISSUE TITLE
请教下，怎么配置对具体的URL统计和监控呢

### ISSUE THREAD

**Issue by xuanskyer** [vovolie/lua-nginx-prometheus#2]
就像你的截图当中，我看到是对具体的某些API接口URL做了监控，这些具体该如何配置呢？
我按照你的这个流程操作下来，但是发现并没有针对URL的统计

**Comment by vovolie** [comment]
具体的接口和域名是存放在了consol的kv里面，openresty会在nginx的log阶段对照域名和接口，进行统计的。

**Comment by xuanskyer** [comment]
@vovolie 这个必须用openresty么，支持lua模块的nginx可以不？

**Comment by vovolie** [comment]
可以的。

**Comment by xuanskyer** [comment]
不知道这个仓库的readme和代码是同步的么？
我按照你的步骤，还是无法统计成功指定URL

**Comment by vovolie** [comment]
这个问题有点难定位，可以在lua里面输出指定点的log，例如consul里面定时取KV里面的值，是否正确拿到。里面有个Domain的Key里面是存放着指定域名的数组。
