### ISSUE TITLE
是否支持tengine?

### ISSUE THREAD

**Issue by inxming** [vovolie/lua-nginx-prometheus#5]
是否支持tengine version2.2.0?

**Comment by vovolie** [comment]
没试过tengine，使用openresty会好一些吧。理论上能跑lua的都可以。

**Comment by inxming** [comment]
README.md里面的dashboard是否上传到了官网? 
主要想了解一下请求耗时25%,50%,75%,95%的query example 是否可以分享一下

**Comment by vovolie** [comment]
dashboard没有上传，自己配的
histogram_quantile(0.50, sum(rate(nginx_http_request_duration_seconds_bucket{host="$host",endpoint="$endpoint",status!="101"}[$interval])) by (le))

$符号的是grafana的变量，101是websocket的状态。

**Comment by inxming** [comment]
感谢:)
因为没有openresty测试,我拿同样的方式查询了一下网卡流量  发现是nodata? 
query:
  histogram_quantile(0.50,sum by (app) (irate(node_network_transmit_bytes{app="$service", device="eth0"}[5m])))
  histogram_quantile(0.50,sum(rate(node_network_transmit_bytes{app="$service", device="eth0"}[5m])) by (app))

**Comment by vovolie** [comment]
只能应用于histogram类型，le的分桶是要有的

**Comment by inxming** [comment]
thx!
