### ISSUE TITLE
请教grafana如何配置呢?

### ISSUE THREAD

**Issue by tweyseo** [vovolie/lua-nginx-prometheus#6]
在datasource里
HTTP的URL配置http://ip:port或者http://ip:port/metrics
Access配置Browser
save&test的时候 就一个红色的叹号 没错误信息
不懂是哪里配错了?

**Comment by vovolie** [comment]
在grafana 里面 datasource 应该指到prometheus里面，不是直接openresty 暴露的metrices拉置。
